### PR TITLE
Update to readme

### PR DESCRIPTION
**Pull request by jhumeey**
## Description
Updated the README.md file with the project description.

Fixes #(issue number 2) 

## Checklist:
- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dabsclement — CHANGES_REQUESTED** [review]
you still need to fix the indentation error

**Review by dabsclement — APPROVED** [review]
Good, all indentation error fix

**Review by dabsclement — APPROVED** [review]
Good, this fix all indentation issues

**Review by AdekunleDally — APPROVED** [review]
The file was well documented and the content explanatory

**Review by doncity-tech — APPROVED** [review]

**Pull request merged**
